apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-app-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: amazon-app
  template:
    metadata:
      labels:
        app: amazon-app
    spec:
      containers:
        - name: amazon
          image: mradulsingh25/amazon-app:latest  # Use your actual Docker image name and tag
          ports:
            - containerPort: 3000  # The port your React app is listening on

---
apiVersion: v1
kind: Service
metadata:
  name: amazon-app-service
spec:
  selector:
    app: amazon-app
  ports:
    - protocol: TCP
      port: 80  # The port exposed by the service within the cluster
      targetPort: 3000  # The port your React app is listening on inside the pod
  type: LoadBalancer
